"""
A list of ICD-10 *block*-level diagnosis descriptions.

The paper represents diagnoses at ICD-10 block level (not individual codes), e.g.
"Hypertensive diseases" rather than "I10 Essential (primary) hypertension". The
descriptions below are standard WHO ICD-10 block titles. The subset marked as
"confirmed" was recovered verbatim from column headers / printed output in the
original (now-lost) preprocessing notebooks; the rest are standard ICD-10 block
titles added so the synthetic dataset has a realistic number of diagnosis columns
(the real cohort had well over 100).

This list is used ONLY to generate synthetic/smoke-test data -- it has no bearing
on the real UK Biobank cohort's actual diagnosis columns.
"""

# Recovered verbatim from the original notebooks (column names / printed sequences)
CONFIRMED_BLOCKS = [
    "Hypertensive diseases",
    "Arthropathies",
    "Diseases of oesophagus, stomach and duodenum",
    "General symptoms and signs",
    "Symptoms, signs and abnormal clinical and laboratory findings, not elsewhere classified",
    "Factors influencing health status and contact with health services",
    "Diabetes mellitus",
    "Disorders of lens",
    "Mood [affective] disorders",
    "Chronic lower respiratory diseases",
    "Nutritional anaemias",
    "Other diseases of intestines",
    "Other soft tissue disorders",
    "Disorders of thyroid gland",
    "Disorders of nails and hair",
    "Disorders of bone density and structure",
    "Symptoms and signs involving the digestive system and abdomen",
    "Other diseases of digestive system",
    "Abnormal findings on examination of blood, without diagnosis",
    "Abnormal findings on examination of other body fluids, without diagnosis",
    "Abnormal findings on examination of other systems, not elsewhere classified",
    "Abnormal findings on examination of urine, without diagnosis",
]

# Additional standard ICD-10 block titles, added to reach a realistic column count
ADDITIONAL_BLOCKS = [
    "Intestinal infectious diseases",
    "Other bacterial diseases",
    "Viral infections characterized by skin and mucous membrane lesions",
    "Viral hepatitis",
    "Malignant neoplasm of digestive organs",
    "Malignant neoplasm of respiratory and intrathoracic organs",
    "Malignant neoplasm of breast",
    "Malignant neoplasm of female genital organs",
    "Malignant neoplasm of male genital organs",
    "Malignant neoplasm of urinary tract",
    "Neoplasms of uncertain or unknown behaviour",
    "Other nutritional deficiencies",
    "Metabolic disorders",
    "Other anaemias",
    "Coagulation defects, purpura and other haemorrhagic conditions",
    "Other diseases of blood and blood-forming organs",
    "Dementia",
    "Other disorders of the nervous system",
    "Episodic and paroxysmal disorders",
    "Nerve, nerve root and plexus disorders",
    "Polyneuropathies and other disorders of the peripheral nervous system",
    "Disorders of conjunctiva",
    "Disorders of choroid and retina",
    "Glaucoma",
    "Cataract",
    "Diseases of the ear and mastoid process",
    "Ischaemic heart diseases",
    "Other forms of heart disease",
    "Cardiac arrhythmias",
    "Heart failure",
    "Cerebrovascular diseases",
    "Diseases of arteries, arterioles and capillaries",
    "Diseases of veins, lymphatic vessels and lymph nodes, not elsewhere classified",
    "Acute upper respiratory infections",
    "Influenza and pneumonia",
    "Other acute lower respiratory infections",
    "Other diseases of upper respiratory tract",
    "Chronic diseases of tonsils and adenoids",
    "Other diseases of the respiratory system",
    "Diseases of oral cavity, salivary glands and jaws",
    "Diseases of appendix",
    "Hernia",
    "Noninfective enteritis and colitis",
    "Diseases of liver",
    "Disorders of gallbladder, biliary tract and pancreas",
    "Other diseases of the digestive system",
    "Infections of the skin and subcutaneous tissue",
    "Other disorders of the skin and subcutaneous tissue",
    "Dermatitis and eczema",
    "Papulosquamous disorders",
    "Diseases of skin appendages",
    "Systemic connective tissue disorders",
    "Dorsopathies",
    "Soft tissue disorders",
    "Osteopathies and chondropathies",
    "Diseases of the genitourinary system",
    "Glomerular diseases",
    "Renal tubulo-interstitial diseases",
    "Renal failure",
    "Urolithiasis",
    "Other disorders of kidney and ureter",
    "Other diseases of urinary system",
    "Diseases of male genital organs",
    "Disorders of breast",
    "Inflammatory diseases of female pelvic organs",
    "Noninflammatory disorders of female genital tract",
    "Complications of pregnancy, childbirth and the puerperium",
    "Certain conditions originating in the perinatal period",
    "Congenital malformations of the circulatory system",
    "Congenital malformations of the digestive system",
    "Chromosomal abnormalities, not elsewhere classified",
    "Fracture of forearm",
    "Fracture involving multiple regions of lower limb",
    "Dislocation, sprain and strain of joints and ligaments",
    "Injury of nerves and spinal cord",
    "Superficial injury",
    "Open wound",
    "Effects of foreign body entering through natural orifice",
    "Burns and corrosions",
    "Poisoning by drugs, medicaments and biological substances",
    "Complications of surgical and medical care, not elsewhere classified",
    "Persons with potential health hazards related to communicable diseases",
    "Persons encountering health services for examination and investigation",
    "Persons with potential health hazards related to family and personal history",
    "Persons encountering health services in other circumstances",
    "Schizophrenia, schizotypal and delusional disorders",
    "Neurotic, stress-related and somatoform disorders",
    "Behavioural syndromes associated with physiological disturbances and physical factors",
    "Disorders of adult personality and behaviour",
    "Mental retardation",
    "Disorders of psychological development",
    "Sleep disorders",
    "Extrapyramidal and movement disorders",
    "Other degenerative diseases of the nervous system",
    "Demyelinating diseases of the central nervous system",
    "Epilepsy",
    "Migraine",
    "Disorders of autonomic nervous system",
    "Rheumatoid arthritis and other inflammatory polyarthropathies",
    "Other joint disorders",
    "Systemic atrophies primarily affecting the central nervous system",
    "Obesity and other hyperalimentation",
    "Other endocrine disorders",
    "Disorders of other endocrine glands",
    "Volume depletion",
    "Disorders of fluid, electrolyte and acid-base balance",
]

ICD10_BLOCKS = CONFIRMED_BLOCKS + ADDITIONAL_BLOCKS
